server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

    dbcp2:
      initial-size: 1
      min-idle: 1
      max-idle: 20
      test-on-borrow: true

#mybatis
mybatis:
  type-aliases-package: com.batis.pojo
  mapper-locations: classpath:mapper/*.xml

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.batis.utils.MyMapper
  not-empty: false
  identity: MYSQL
